---

- name: install icinga2 web packages
  package:
    name: '{{ icinga2_web_packages }}'
    state: present

# Allow httpd to connect to the mysql database
- name: set httpd_can_network_connect_db flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  when: ansible_selinux and ansible_selinux.status == "enabled"

# Allow httpd to connect to the network
- name: set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux and ansible_selinux.status == "enabled"

- name: check if icingaweb2 table and user in mysql exist
  shell: >
    set -o pipefail;
    mysql
    --user={{ icinga2_web_database_root_user }}
    --password={{ icinga2_web_database_root_pass }}
    --host={{ icinga2_web_icingaweb2_database_host }}
    --ssl-ca={{ icinga2_web_ca_path }}
    {{ icinga2_web_icingaweb2_database_name }}
    -e "SHOW TABLES;" | grep "icingaweb_user"
  register: icinga2_web_register_icingaweb2_imported
  changed_when: icinga2_web_register_icingaweb2_imported.rc == 1
  failed_when: "'Access denied for' in icinga2_web_register_icingaweb2_imported.stderr"

- name: import icingaweb2 database schema using the root user
  mysql_db:
    name: '{{ icinga2_web_icingaweb2_database_name }}'
    login_host: '{{ icinga2_web_icingaweb2_database_host }}'
    login_port: '{{ icinga2_web_icingaweb2_database_port }}'
    login_user: '{{ icinga2_web_database_root_user }}'
    login_password: '{{ icinga2_web_database_root_pass }}'
    ssl_ca: '{{ icinga2_web_ca_path }}'
    state: import
    target: '{{ icinga2_web_mysql_schema_sql_path }}'
  run_once: True
  when:
    - not ansible_check_mode
    - icinga2_web_register_icingaweb2_imported.rc == 1

- name: create a user with access only to the icingaweb2 database using the root user
  mysql_user:
    name: '{{ icinga2_web_icingaweb2_database_user.split("@")[0] }}'
    password: '{{ icinga2_web_icingaweb2_database_pass }}'
    priv: '{{ icinga2_web_icingaweb2_database_name }}.*:ALL'
    host: '{{ icinga2_web_icingaweb2_database_hostpattern }}'
    login_host: '{{ icinga2_web_icingaweb2_database_host }}'
    login_port: '{{ icinga2_web_icingaweb2_database_port }}'
    login_user: '{{ icinga2_web_database_root_user }}'
    login_password: '{{ icinga2_web_database_root_pass }}'
    ssl_ca: '{{ icinga2_web_ca_path }}'
    state: present
  run_once: True
  when:
    - not ansible_check_mode
    - icinga2_web_register_icingaweb2_imported.rc == 1

- name: ensure icingaweb2 modules directory is present
  file:
    name: /etc/icingaweb2/enabledModules
    state: directory
    owner: root
    group: icingaweb2
    mode: 0755

- name: ensure icingaweb2 modules directory is present and set selinux
  file:
    name: /etc/icingaweb2/enabledModules
    state: directory
    owner: root
    group: icingaweb2
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: icingaweb2_config_t
    selevel: s0
  notify: icinga2_web reload icinga2

- name: install modules from github
  git: # noqa 401
    repo: 'https://github.com/icinga/icingaweb2-module-{{ item.name }}.git'
    dest: '/etc/icingaweb2/modules/{{ item.name }}'
    version: '{{ item.version }}'
  loop: '{{ icinga2_web_modules }}'
  notify: icinga2_web reload icinga2

- name: enable modules from github
  file:
    src: '/etc/icingaweb2/modules/{{ item.name }}'
    dest: '/etc/icingaweb2/enabledModules/{{ item.name }}'
    state: link
    mode: 0755
  loop: '{{ icinga2_web_modules }}'
  notify: icinga2_web reload icinga2

- name: create icingaweb2 director user for background daemon
  user:
    name: icingadirector
    group: icingaweb2
    shell: '/bin/false'
    home: '/var/lib/icingadirector'
    system: yes
  when: icinga2_web_director | length != 0

- name: create home directory for icingaweb2 director daemon user
  file:
    name: /var/lib/icingadirector
    state: directory
    owner: icingadirector
    group: icingaweb2
    mode: 0750
    seuser: system_u
    serole: object_r
    setype: var_lib_t
    selevel: s0
  when: icinga2_web_director | length != 0

- name: install systemd service for icingaweb2 director daemon
  copy:
    src: /etc/icingaweb2/modules/director/contrib/systemd/icinga-director.service
    remote_src: yes
    dest: /etc/systemd/system
    mode: 0644
  when: icinga2_web_director | length != 0

- name: enable and start systemd service for icingaweb2 director daemon
  systemd:
    name: icinga-director.service
    state: started
    daemon_reload: yes
    enabled: yes
  when: icinga2_web_director | length != 0

- name: add grafana repository
  yum_repository:
    name: grafana
    description: grafana
    baseurl: https://packages.grafana.com/oss/rpm
    repo_gpgcheck: yes
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.grafana.com/gpg.key
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
  when: icinga2_web_grafana.enabled

- name: install grafana
  yum:
    name: grafana
    state: present
  when: icinga2_web_grafana.enabled

- name: enable and start grafana service
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
    enabled: yes
  when: icinga2_web_grafana.enabled
